'use client'

import LeadChange from '@/app/homecomponents/LeadChange'
import Header from '@/app/components/Header'
import Hero from './components/Hero'
import Footer from '@/app/components/Footer'
import ServicesSection from '../service'
import { ServiceItem } from '@/app/types/service'
import React from 'react'
import Testimonials, { Testimonial } from '@/app/components/Testimonials'
import FAQ from '@/app/components/FAQ'
import StickyNavigation from '@/app/components/StickyNavigation'
import KeyFeatures from '@/app/components/KeyFeatures'

const aiDesignerTestimonials: Testimonial[] = [
  {
    id: 1,
    body: "Game-changer for consultations. I upload a photo during our meeting and show 5 different design directions instantly. Clients are blown away. What used to take a week of back-and-forth now happens in real-time.",
    clientName: "Marcus Johnson",
    clientCompany: "Johnson Renovations"
  },
  {
    id: 2,
    body: "The AI understands construction constraints. It doesn\'t suggest removing load-bearing walls or impossible layouts. Every design it generates is actually buildable, saving tons of revision time.",
    clientName: "Sarah Mitchell",
    clientCompany: "Mitchell Design Build"
  },
  {
    id: 3,
    body: "We use it for quick quotes. Client sends a photo, we run it through AI for design options, and send a ballpark estimate with visuals same day. Our response time beats every competitor.",
    clientName: "Tony Deluca",
    clientCompany: "Deluca Brothers Construction"
  },
  {
    id: 4,
    body: "The style variations are incredible. Modern, traditional, transitional, industrial – all from one photo. Helps clients who don\'t know what they want see possibilities. Upsells happen naturally.",
    clientName: "Emma Thompson",
    clientCompany: "Thompson Interiors & Remodeling"
  },
  {
    id: 5,
    body: "ROI is insane. Won a $200K whole-home remodel because I could show the vision faster than competitors. The AI designs were so good, the client hired us on the spot.",
    clientName: "Robert Chen",
    clientCompany: "Chen Custom Homes"
  },
  {
    id: 6,
    body: "It learns our style preferences. The more we use it, the better it gets at generating designs that match our brand. Feels like having a whole design team working 24/7.",
    clientName: "Jessica Adams",
    clientCompany: "Adams Architectural Remodeling"
  }
];

const aiDesignerServices: ServiceItem[] = [
  {
    id: 'instant-redesign',
    title: 'Instant Room Redesign & Remodeling',
    description: 'Transform any room in seconds with AI-powered redesign. Simply upload a photo and watch as our AI generates multiple professional design concepts. Choose from dozens of styles – modern, farmhouse, contemporary, traditional, minimalist, or luxury. Each design maintains the room\'s structure while completely reimagining finishes, fixtures, and furnishings. Perfect for showing clients the potential of their space during initial consultations.',
    buttonText: 'Try Room Redesign',
    buttonHref: '/tools/room-redesign',
    imageSrc: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2800&auto=format&fit=crop',
    imageAlt: 'AI-generated room redesign variations',
    priority: true,
    imageSizes: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 45vw',
    imageQuality: 90
  },
  {
    id: 'style-explorer',
    title: 'Multi-Style Design Explorer',
    description: 'Show clients their space in every possible style instantly. Our AI generates the same room in modern, traditional, industrial, Mediterranean, Scandinavian, bohemian, and more. Clients can compare styles side-by-side, mix elements they like, and find their perfect aesthetic. This powerful tool eliminates style uncertainty and helps clients commit to bigger, more confident renovation decisions.',
    buttonText: 'Explore Styles',
    buttonHref: '/tools/style-explorer',
    imageSrc: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=2758&auto=format&fit=crop',
    imageAlt: 'Multiple design styles generated by AI',
    imageSizes: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 45vw',
    imageQuality: 90
  },
  {
    id: 'kitchen-bath-ai',
    title: 'Kitchen & Bathroom AI Specialist',
    description: 'Specialized AI trained specifically on kitchen and bathroom designs – your most profitable projects. Generate layouts that maximize space, suggest cabinet configurations, visualize different countertop materials, and explore fixture options. The AI understands plumbing constraints, electrical requirements, and building codes. Create stunning kitchen islands, walk-in showers, double vanities, and more with construction-ready designs.',
    buttonText: 'Design Kitchen/Bath',
    buttonHref: '/tools/kitchen-bath-ai',
    imageSrc: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=2670&auto=format&fit=crop',
    imageAlt: 'AI-designed kitchen and bathroom concepts',
    imageSizes: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 45vw',
    imageQuality: 85
  }
]

const aiDesignerFAQs = [
  {
    id: 'faq-1',
    question: 'How quickly can the AI generate design concepts?',
    answer: 'Designs are generated in 10-30 seconds. Upload a photo, select preferences, and get multiple professional design options instantly. Most contractors use it live during client consultations to explore ideas in real-time. No waiting, no delays – immediate visual results that wow clients.'
  },
  {
    id: 'faq-2',
    question: 'Are the AI designs actually buildable and code-compliant?',
    answer: 'Yes! Our AI is trained on real construction projects and understands building constraints. It won\'t suggest removing load-bearing walls, impossible plumbing layouts, or code violations. Every design is practical and buildable. The AI considers room dimensions, structural elements, and standard construction practices.'
  },
  {
    id: 'faq-3',
    question: 'Can I customize the AI designs after they\'re generated?',
    answer: 'Absolutely! Think of AI designs as your starting point. You can modify colors, swap materials, adjust layouts, and fine-tune every detail. Mix elements from different generated designs, save your favorites, and create unlimited variations. The AI speeds up the creative process without limiting your control.'
  },
  {
    id: 'faq-4',
    question: 'What makes this better than traditional design software?',
    answer: 'Speed and simplicity. No learning curve, no complex software, no hours of manual work. Generate in seconds what traditionally takes hours or days. Show clients multiple fully-realized options immediately instead of rough sketches. The AI handles the technical work while you focus on selling and client relationships.'
  },
  {
    id: 'faq-5',
    question: 'Can clients use the AI Designer directly?',
    answer: 'You control access. Some contractors let clients explore options through a branded portal, while others use it exclusively during consultations. When clients can play with designs themselves, they get more excited and emotionally invested in the project, leading to faster decisions and bigger budgets.'
  },
  {
    id: 'faq-6',
    question: 'Does the AI work for both interior and exterior projects?',
    answer: 'Yes! The AI handles everything from bathroom remodels to complete home exteriors. It can redesign kitchens, living rooms, bedrooms, basements, and outdoor spaces. It visualizes siding, roofing, landscaping, and additions. One tool for all your design needs, whether inside or outside the home.'
  }
]

const AIDesignerPage = () => {
  const handleServiceInquiry = (serviceId: string) => {
    console.log(`Inquiry for service: ${serviceId}`)
    // Add navigation or modal logic here
  }

  const navigationItems = [
    { id: 'key-features', label: 'Key Features' },
    { id: 'services', label: 'Services' },
    { id: 'testimonials', label: 'Success Stories' },
    { id: 'faq', label: 'FAQs' },
    { id: 'why-lattice', label: 'Why Lattice' },
    { id: 'contact', label: 'Get Started' }
  ]

  const keyFeatures = [
    {
      number: 1,
      title: 'Instant Design Concepts',
      description: 'Generate multiple professional design options in 10-30 seconds. Upload a photo and watch AI create stunning variations in modern, traditional, farmhouse, and luxury styles instantly.'
    },
    {
      number: 2,
      title: 'Actually Buildable Designs',
      description: 'AI trained on real construction projects understands building constraints. No impossible layouts or code violations—every design is practical, buildable, and ready for implementation.'
    },
    {
      number: 3,
      title: 'Live Client Consultations',
      description: 'Show clients design possibilities in real-time during meetings. Explore multiple styles, materials, and layouts on the spot. No waiting, no callbacks—close deals faster with instant visualization.'
    },
    {
      number: 4,
      title: 'Unlimited Variations',
      description: 'Mix and match elements from different designs. Try unlimited color schemes, materials, and layouts without additional costs. Perfect designs through rapid iteration, not guesswork.'
    }
  ]

  return (
    <div className="pt-5">
      <Header />
      <div id="hero">
        <Hero />
      </div>
      <StickyNavigation items={navigationItems} />
      <div id="key-features">
        <KeyFeatures features={keyFeatures} />
      </div>
      <div id="services">
        <ServicesSection
          services={aiDesignerServices}
          sectionId="ai-designer-features"
          sectionClassName="bg-gradient-to-b from-white to-gray-50"
          onButtonClick={handleServiceInquiry}
          headingLevel="h2"
          lazyLoadImages={true}
          animateOnScroll={true}
        />
      </div>
      <div id="testimonials">
        <Testimonials
          testimonials={aiDesignerTestimonials}
          title="AI Success Stories"
          subtitle="How Contractors Win with AI-Powered Design"
        />
      </div>
      <div id="faq">
        <FAQ
          items={aiDesignerFAQs}
          title="AI Designer FAQs"
          subtitle="Learn how AI transforms your design process"
          schemaOrg={true}
        />
      </div>
      <div id="why-lattice">
        {/* Why Lattice section - can add content here later */}
      </div>
      <div id="contact">
        <LeadChange text="Start Designing with AI Today"/>
      </div>
      <Footer />
    </div>
  )
}

export default AIDesignerPage