import type { Metadata } from "next";
import { Figtree } from 'next/font/google';
import "./globals.css";
import { MegaMenuProvider } from "./contexts/MegaMenuContext";
import MegaMenuOverlay from "./components/MegaMenuOverlay";

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-figtree',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.variable}>
      <body className={`${figtree.className} antialiased tracking-tighter`} suppressHydrationWarning>
        <MegaMenuProvider>
          <MegaMenuOverlay />
          {children}
        </MegaMenuProvider>
      </body>
    </html>
  );
}
